services:
  # 1. MONGODB (Database)
  mongo:
    image: mongo:latest
    container_name: taw_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - taw_network

  # 2. BACKEND (Node.js API)
  backend:
    build: ./taw-backend
    container_name: taw_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taw_project
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./taw-backend:/app          # Sincronizza il codice
      - /app/node_modules       # Evita di sovrascrivere i node_modules del container
    networks:
      - taw_network

  # 3. FRONTEND (Angular)
  frontend:
    build: ./taw-frontend
    container_name: taw_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./taw-frontend:/app         # Sincronizza il codice
      - /app/node_modules       # Protegge i node_modules interni
    networks:
      - taw_network

networks:
  taw_network:

volumes:
  mongo_data: